# Generated by Django 4.2.2 on 2023-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_auto_20210213_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blooddonate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
