# Generated by Django 5.0.1 on 2024-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_alter_donor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
