# Generated by Django 5.0.1 on 2024-02-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
