# Generated by Django 5.0.1 on 2024-02-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("donor", "Donor")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
